// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SinhVien.Model.FE;

#nullable disable

namespace SinhVien.Model.Migrations
{
    [DbContext(typeof(SinhVienDbcontext))]
    partial class SinhVienDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SinhVien.Model.Entity.Appconfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppConfigs", (string)null);
                });

            modelBuilder.Entity("SinhVien.Model.Entity.DiemThiET", b =>
                {
                    b.Property<int>("MaSVId")
                        .HasColumnType("int");

                    b.Property<int>("MaMHId")
                        .HasColumnType("int");

                    b.Property<float>("DiemThi")
                        .HasColumnType("real");

                    b.Property<int>("LanThi")
                        .HasColumnType("int");

                    b.HasKey("MaSVId", "MaMHId");

                    b.HasIndex("MaMHId");

                    b.ToTable("DiemThi", (string)null);
                });

            modelBuilder.Entity("SinhVien.Model.Entity.GiangVienET", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuyenNganh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KhoaId")
                        .HasColumnType("int");

                    b.Property<string>("TenGV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("GiangVien", (string)null);
                });

            modelBuilder.Entity("SinhVien.Model.Entity.KhoaET", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Khoa", (string)null);
                });

            modelBuilder.Entity("SinhVien.Model.Entity.LopET", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhoaId")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("Lop", (string)null);
                });

            modelBuilder.Entity("SinhVien.Model.Entity.MonHocET", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SoTiet")
                        .HasColumnType("int");

                    b.Property<string>("TenMH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("SinhVien.Model.Entity.SinhVienET", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LopId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LopId");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("SinhVien.Model.Entity.DiemThiET", b =>
                {
                    b.HasOne("SinhVien.Model.Entity.MonHocET", "MonHocET")
                        .WithMany("DiemThiETs")
                        .HasForeignKey("MaMHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DiemThi-MonHoc");

                    b.HasOne("SinhVien.Model.Entity.SinhVienET", "SinhVienET")
                        .WithMany("DiemThiETs")
                        .HasForeignKey("MaSVId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DiemThi-SinhVien");

                    b.Navigation("MonHocET");

                    b.Navigation("SinhVienET");
                });

            modelBuilder.Entity("SinhVien.Model.Entity.GiangVienET", b =>
                {
                    b.HasOne("SinhVien.Model.Entity.KhoaET", "KhoaET")
                        .WithMany("GiangVienETs")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GiangVien_Khoa");

                    b.Navigation("KhoaET");
                });

            modelBuilder.Entity("SinhVien.Model.Entity.LopET", b =>
                {
                    b.HasOne("SinhVien.Model.Entity.KhoaET", "KhoaET")
                        .WithMany("LopETs")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Lop_Khoa");

                    b.Navigation("KhoaET");
                });

            modelBuilder.Entity("SinhVien.Model.Entity.SinhVienET", b =>
                {
                    b.HasOne("SinhVien.Model.Entity.LopET", "LopET")
                        .WithMany("SinhVienETs")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PK_SinhVien_Lop");

                    b.Navigation("LopET");
                });

            modelBuilder.Entity("SinhVien.Model.Entity.KhoaET", b =>
                {
                    b.Navigation("GiangVienETs");

                    b.Navigation("LopETs");
                });

            modelBuilder.Entity("SinhVien.Model.Entity.LopET", b =>
                {
                    b.Navigation("SinhVienETs");
                });

            modelBuilder.Entity("SinhVien.Model.Entity.MonHocET", b =>
                {
                    b.Navigation("DiemThiETs");
                });

            modelBuilder.Entity("SinhVien.Model.Entity.SinhVienET", b =>
                {
                    b.Navigation("DiemThiETs");
                });
#pragma warning restore 612, 618
        }
    }
}
